name: Update Configs

on:
  schedule:
    # Run every 10 minutes
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script and save output to file
      run: python app.py > configs.txt

    - name: Commit and push files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update configs.txt
        file_pattern: configs.txt
        branch: main
      env:
        GITHUB_TOKEN: ${{ secrets.YOUR_TOKEN }}
