name: Python application

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run application and save output to file
      run: |
        source env/bin/activate
        python app.py > configs.txt

    - name: Configure git
      run: |
        git config --global user.name 'Github Actions'
        git config --global user.email 'actions@github.com'

    - name: Push changes to repository
      env:
        ACCESS_TOKEN: ${{ secrets.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 }}
      run: |
        git remote set-url origin https://Bardiafa:${{ env.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 }}@github.com/Bardiafa/Free-V2ray-Config.git
        git add configs.txt
        git commit -m "Update configs.txt"
        git push origin main
