name: Update Configs

on:
  push:
    branches:
      - main
  schedule:
    # Run every 10 minutes
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script and save output to file
      run: python app.py > configs.txt

    - name: Commit and push files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "Github Actions" 
        author_email: "actions@github.com"
        message: "Update configs.txt"
        add: "."
        push: "https://github.com/Bardiafa/Free-V2ray-Config.git"
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
