name: Splitter
permissions: write-all

on:
  workflow_dispatch:
    inputs:
      delay_minutes:
        description: 'Delay in minutes'
        required: true
        default: 5
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script and save output to file
      run: python sort.py

    - name: Commit and push files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "Github Actions" 
        author_email: "actions@github.com"
        message: "Sorted 9 minutes Ago. 🎇"
        add: "."
        push: "https://github.com/Bardiafa/Free-V2ray-Config.git"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
