name: My SSH workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-known-hosts: github.com
    - name: Test SSH connection
      run: |
        eval `ssh-agent -s`
        ssh-add - <<<"${{ secrets.SSH_PRIVATE_KEY }}"
        ssh -T git@github.com
